server:
  addr: "127.0.0.1:8080"
routes:
 
  - name: "public_service"
    path: "/public"
    destination: "https://httpbin.org/anything"
  
  - name: "admin_service"
    path: "/jwt/admin"
    destination: "https://httpbin.org/anything"
    auth:
      type: "Jwt"
      roles:
        - "admin"

  - name: "user_service"
    path: "/api/user"
    destination: "https://httpbin.org/anything"
    auth:
      type: "ApiKey"
      roles:
        - "user"
  
  - name: "admin_service"
    path: "/api/admin"
    destination: "https://httpbin.org/anything"
    auth:
      type: "ApiKey"
      roles:
        - "admin"
    
